KinsonDigital/Infrastructure

- .github/ISSUE_TEMPLATE/project-item-issue-template.yml
- .github/PULL_REQUEST_TEMPLATE/feature-pr.md
- .github/workflows/resolve-csharp-proj-file.yml
> Create re-usable workflow to resolve project files

- .github/ISSUE_TEMPLATE/project-item-issue-template.yml
- .github/workflows/run-csharp-tests.yml
> 🚧Fix issue with unit test workflow

- .github/workflows/build-csharp-project.yml
- .github/workflows/run-csharp-tests.yml
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>
``` xml
```
</details>
💡For more information on branching, refer to the project's [branching documentation](https://github.com/KinsonDigital/.github/blob/master/docs/Branching.md).
- The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's discuss it. …
> 🚧Update action version in workflows

- .vscode/launch.json
- cicd/core/MilestoneClient.ts
- cicd/scripts/add-item-to-project.ts
- cicd/scripts/close-milestone.ts
- cicd/scripts/label-if-head-branch.ts
- cicd/scripts/milestone-exists.ts
- cicd/scripts/milestone-items-all-closed.ts
- cicd/scripts/release-notes-exist.ts
- cicd/scripts/validate-release-notes.ts
- cicd/scripts/validate-tag.ts
- cicd/scripts/validate-version.ts
- deno.lock
> 🚧Create script to validate versions 

- cicd/scripts/add-item-to-project.ts
- cicd/scripts/close-milestone.ts
- cicd/scripts/label-if-head-branch.ts
- cicd/scripts/milestone-exists.ts
- cicd/scripts/milestone-items-all-closed.ts
- cicd/scripts/release-notes-exist.ts
- cicd/scripts/validate-release-notes.ts
- cicd/scripts/validate-tag.ts
- cicd/scripts/validate-version.ts
> 🚧Remove script description code

- cicd/core/Types.ts
- cicd/scripts/add-item-to-project.ts
> 🚧Fix logging issue

- .vscode/launch.json
- cicd/core/Directory.ts
- cicd/core/File.ts
- cicd/core/Models/ITwitterAuthValues.ts
- cicd/core/ReleaseTweetBuilder.ts
- cicd/core/ScriptDescriptions.ts
- cicd/core/TwitterClient.ts
- cicd/core/Utils.ts
- cicd/release-tweet-template.txt
- cicd/scripts/release-notes-exist.ts
- cicd/scripts/send-release-tweet.ts
- cicd/scripts/validate-tag.ts
- cicd/scripts/validate-version.ts
- deno.lock
> 🚧Create twitter announcement script

- cicd/scripts/validate-version.ts
> 🚧Sanitize script version argument

- cicd/scripts/validate-tag.ts
> 🚧Fix validate tag args

- cicd/scripts/nuget-pkg-does-not-exist.ts
> 🚧Fix args checking issue

- cicd/scripts/release-notes-exist.ts
> 🚧Fix release type arg checks

- cicd/clients/PullRequestClient.ts
- cicd/core/Utils.ts
- cicd/scripts/add-item-to-project.ts
- http-requests/github-requests.http
> 🚧Fix a bug when the pr client url

- .github/workflows/sync-bot-status-check.yml
- .github/workflows/sync-issue-to-pr.yml
- .github/workflows/validate-milestone-status.yml
- .github/workflows/validate-release-notes.yml
- .github/workflows/validate-tag.yml
- cicd/clients/OrgClient.ts
- cicd/clients/ProjectClient.ts
- cicd/clients/RepoClient.ts
- cicd/core/GraphQLClient.ts
- cicd/core/Models/IOrgVarModel.ts
- cicd/core/Models/IOrgVariablesModel.ts
- cicd/core/Models/IRepoVarModel.ts
- cicd/core/Models/IRepoVariablesModel.ts
- cicd/scripts/runners/SyncBotStatusCheckRunner.ts
- cicd/scripts/sync-issue-to-pr.ts
This pull request closes #63
✅ At a minimum, the user @KinsonDigitalAdmin has been requested to review this pull request.  …
> 🚧Add improvements

- cicd/scripts/runners/SyncBotStatusCheckRunner.ts
This pull request closes #67
✅ At a minimum, the user @KinsonDigitalAdmin has been requested to review this pull request.  …
> 🚧Fix status check arg processing

- cicd/clients/LabelClient.ts
This pull request closes #72
✅ At a minimum, the user @KinsonDigitalAdmin has been requested to review this pull request.  …
> 🚧Fix label client bug

- .github/workflows/validate-release-notes.yml
This pull request closes #70
❌ At a minimum, the user @KinsonDigitalAdmin has been requested to review this pull request.  …
> 🚧Simple improvements

- .github/workflows/sync-bot-status-check.yml
- .github/workflows/sync-issue-to-pr.yml
- cicd/core/IPRTemplateSettings.ts
- cicd/core/PRTemplateManager.ts
- cicd/scripts/runners/SyncBotStatusCheckRunner.ts
- cicd/scripts/sync-issue-to-pr.ts
- cicd/templates/pr-sync-status-template.txt
This pull request closes #69
✅ At a minimum, the user @KinsonDigitalAdmin has been requested to review this pull request.  …
> 🚧Remove reviewer as status check

- .github/workflows/release.yml
This pull request closes #75
--- …
> 🚧Fix step if logic for dry runs

- cicd/scripts/runners/SyncBotStatusCheckRunner.ts
This pull request closes #86
--- …
> 🚧Fix incorrect sync status report

- .github/ISSUE_TEMPLATE/project-item-issue-template.yml
- .vscode/launch.json
- cicd/scripts/runners/SyncBotStatusCheckRunner.ts
This pull request closes #88
--- …
> 🚧Fix pr sync report status issue

- .github/workflows/add-new-issue-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/create-script-url.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/nuget-package-does-not-exist.yml
- .github/workflows/resolve-csharp-proj-file.yml
- .github/workflows/run-csharp-tests.yml
- .github/workflows/sync-bot.yml
- .github/workflows/sync-issue-to-pr.yml
- .github/workflows/sync-status-check.yml
- .github/workflows/validate-csharp-version.yml
- .github/workflows/validate-github-release.yml
- .github/workflows/validate-milestone-status.yml
- .github/workflows/validate-release-notes.yml
- .github/workflows/validate-tag.yml
This pull request closes #103
✅ The pull request base branch must be a 'main' or 'preview' branch. 
--- …
> 🚧Change how release note validation works

- .github/workflows/add-issue-to-project.yml
- .github/workflows/add-new-issue-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/nuget-package-does-not-exist.yml
- .github/workflows/run-csharp-tests.yml
- .github/workflows/validate-csharp-version.yml
- .github/workflows/validate-github-release.yml
- .github/workflows/validate-milestone-status.yml
- .github/workflows/validate-release-notes.yml
- .github/workflows/validate-tag.yml
This pull request closes #105
✅ The pull request base branch must be a 'main' or 'preview' branch. 
--- …
> 🚧Create reusable workflow

- .github/workflows/add-new-issue-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/run-csharp-tests.yml
- cicd/core/GraphQLQueries/GetBranchesQuery.ts
- cicd/scripts/runners/PrepareReleaseRunner.ts
- cicd/scripts/runners/ScriptRunner.ts
This pull request closes #124
--- …
> 🚧Fix branch creation issue

- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- renovate.json
This pull request closes #127
--- …
> 🚧Fix pathing issue in release workflow

- .github/internal-cicd/update-workflow-versions.ts
- .github/internal-cicd/workflow-version-status-check.ts
- .github/workflows/workflow-version-status-check.yml
- .vscode/launch.json
- .vscode/tasks.json
- cicd/clients/RepoClient.ts
- cicd/clients/TagClient.ts
- cicd/playground.ts
- cicd/scripts/runners/ScriptRunner.ts
- deno.lock
This pull request closes #132
--- …
> 🚧Create script version status check

- .github/workflows/add-new-issue-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/run-csharp-tests.yml
- cicd/core/Path.ts
- cicd/scripts/runners/TranspileReadMeRunner.ts
This pull request closes #118
--- …
> 🚧Improve readme transpiling process

- .github/workflows/add-new-issue-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/run-csharp-tests.yml
- cicd/core/Services/GenerateReleaseNotesService.ts
- cicd/core/Services/GitHubVariableService.ts
- cicd/scripts/runners/PrepareReleaseRunner.ts
- cicd/scripts/runners/SendReleaseTweetRunner.ts
- cicd/scripts/runners/SyncBotStatusCheckRunner.ts
- cicd/scripts/runners/SyncPRToIssueRunner.ts
This pull request closes #140
--- …
> 🚧Add release notes content option

- .github/workflows/add-new-item-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/run-csharp-tests.yml
- .github/workflows/sync-pr-to-issue.yml
- .vscode/launch.json
- cicd/core/WebAPIClient.ts
- cicd/scripts/runners/SyncPRToIssueRunner.ts
This pull request closes #168
--- …
> 🚧Improve build and tests workflows

- .github/workflows/add-new-item-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/resolve-csharp-proj-file.yml
- .github/workflows/run-csharp-tests.yml
- .github/workflows/sync-pr-to-issue.yml
- cicd/scripts/resolve-csproj.ts
- cicd/scripts/runners/ResolveCsProjRunner.ts
- cicd/scripts/runners/ScriptRunner.ts
- deno.json
This pull request closes #167
--- …
> 🚧Improve resolve project file workflow

- .github/release-templates/prev-pr-release-template.md
- .github/release-templates/prod-pr-release-template.md
- .github/workflows/add-new-item-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/build-status-check.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/internal-prepare-release.yml
- .github/workflows/run-csharp-tests.yml
- .github/workflows/sync-pr-to-issue.yml
- ReleaseNotes/ProductionReleases/Release-Notes-v13.6.1.md
- deno.json
```[tasklist]
```
```[tasklist]
```
</details>
---
**_<details closed><summary>Version Updating</summary>_**
The version can be updated by setting the values of the `version` JSON value in the `deno.json` file.
``` json
{
"version": "v1.2.3",
...
}
```
</details>
---
> 🚀Production Release (v13.6.1)

- .github/ISSUE_TEMPLATE/project-item-issue-template.yml
- .vscode/settings.json
- cicd/scripts/github-release-does-not-exist.ts
- cicd/scripts/milestone-exists.ts
This pull request closes #210
--- …
> 🚧Fix bug with scripts

- cicd/core/ReleaseTweetBuilder.ts
This pull request closes #214
--- …
> 🚧Fix issue with building tweet

- .github/workflows/add-new-item-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/internal-prepare-release.yml
- .github/workflows/run-csharp-tests.yml
- .github/workflows/sync-pr-to-issue.yml
- ReleaseNotes/ProductionReleases/Release-Notes-v13.6.3.md
- deno.json
```[tasklist]
```
```[tasklist]
```
</details>
---
**_<details closed><summary>Version Updating</summary>_**
The version can be updated by setting the values of the `version` JSON value in the `deno.json` file.
``` json
{
"version": "v1.2.3",
...
}
```
</details>
---
> 🚀Production Release (v13.6.3)

- .github/workflows/resolve-csharp-proj-file.yml
This pull request closes #218
--- …
> 🚧Add repo variable trimming

- .github/ISSUE_TEMPLATE/bug-issue-template.yml
- .github/ISSUE_TEMPLATE/project-item-issue-template.yml
- cicd/core/PRTemplateManager.ts
This pull request closes #226
--- …
> 🚧Fix issue with pr description during initial sync

- .github/workflows/dotnet-lib-release.yml
This pull request closes #225
--- …
> 🚧Change dotnet lib release workflow input to optional

- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
This pull request closes #222
--- …
> 🚧Change github release step

- .github/workflows/dotnet-lib-release.yml
This pull request closes #233
--- …
> 🚧Update dotnet lib release to include debug symbols

- .github/internal-cicd/scripts/update-csharp-proj.ts
- .github/internal-cicd/scripts/update-workflow-versions.ts
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/validate-milestone-status.yml
- .github/workflows/validate-sdk-versions.yml
- .vscode/launch.json
- .vscode/tasks.json
- cicd/scripts/label-if-head-branch.ts
- cicd/scripts/milestone-items-all-closed.ts
- cicd/scripts/mod.ts
This pull request closes #236
--- …
> 🚧Improve dotnet lib release workflow validation

- .vscode/settings.json
- ReleaseNotes/ProductionReleases/Release-Notes-v14.0.0.md
- deno.json
- dev-tools/prev-gen-release-notes-settings.json
- dev-tools/prod-gen-release-notes-settings.json
```[tasklist]
```
```[tasklist]
```
</details>
> 🚀Production Release (v14.0.0)

- .github/workflows/dotnet-lib-release.yml
This pull request closes #243
--- …
> 🚧Fix env vars in dotnet release workflow

- .github/workflows/add-new-item-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/run-csharp-tests.yml
- .github/workflows/sync-pr-to-issue.yml
- deno.json
- release-notes/production-releases/Release-Notes-v14.1.0.md
```[tasklist]
```
```[tasklist]
```
</details>
> 🚀Production Release (v14.1.0)

- .github/workflows/validate-csharp-version.yml
This pull request closes #248
--- …
> 🚧Fix csharp version workflow

- .github/workflows/add-new-item-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/run-csharp-tests.yml
- .github/workflows/sync-pr-to-issue.yml
- deno.json
- release-notes/production-releases/Release-Notes-v14.1.1.md
- templates/prev-prepare-release-template.md
- templates/prod-prepare-release-template.md
```[tasklist]
```
```[tasklist]
```
</details>
> 🚀Production Release (v14.1.1)

- .github/workflows/dotnet-lib-release.yml
- .vscode/settings.json
This pull request closes #251
--- …
> 🚧Update github release step in release workflow

- .github/workflows/add-new-item-to-project.yml
- .github/workflows/build-csharp-project.yml
- .github/workflows/dotnet-action-release.yml
- .github/workflows/dotnet-lib-release.yml
- .github/workflows/run-csharp-tests.yml
- .github/workflows/sync-pr-to-issue.yml
- .vscode/launch.json
- .vscode/tasks.json
- deno.json
- release-notes/production-releases/Release-Notes-v14.2.0.md
```[tasklist]
```
```[tasklist]
```
</details>
> 🚀Production Release (v14.2.0)

- .github/workflows/dotnet-lib-release.yml
- .vscode/launch.json
- cicd/scripts/update-copyright.ts
- deno.json
- deno.lock
This pull request closes #247
--- …
> 🚧Auto update copyright for dotnet projects

- deno.json
- dev-tools/prepare-release-settings.json
- release-notes/production-releases/Release-Notes-v14.3.0.md
- templates/prev-prepare-release-template.md
- templates/prod-prepare-release-template.md
```[tasklist]
```
```[tasklist]
```
</details>
> 🚀Production Release (v14.3.0)

- deno.json
- release-notes/production-releases/Release-Notes-v15.0.0.md
> 🚀Production Release (v15.0.0)
